# Generated by Django 5.1.4 on 2025-12-15 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('default_pack_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TCG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tcgs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('tcg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='core.tcg')),
            ],
            options={
                'db_table': 'sets',
                'ordering': ['tcg', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pack_count', models.IntegerField()),
                ('is_listed', models.BooleanField(default=False)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.producttype')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.set')),
                ('tcg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.tcg')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['tcg', 'set', 'product_type'],
            },
        ),
        migrations.AddIndex(
            model_name='set',
            index=models.Index(fields=['tcg'], name='sets_tcg_id_78dbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tcg'], name='products_tcg_id_2b5207_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['set'], name='products_set_id_db1e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_product_7a7b2f_idx'),
        ),
    ]
