# Generated by Django 5.1.4 on 2025-12-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD')], default='GBP', max_length=3)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('highlight_low_stock_color', models.CharField(default='#FFA500', max_length=7)),
                ('highlight_out_stock_color', models.CharField(default='#FF0000', max_length=7)),
                ('default_date_range', models.CharField(default='30d', max_length=50)),
                ('default_time_aggregation', models.CharField(default='daily', max_length=50)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
