# Generated by Django 5.1.4 on 2025-12-15 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'openings',
                'ordering': ['-opened_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transactions.opening')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_items', to='core.product')),
            ],
            options={
                'db_table': 'opening_line_items',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('vendor', models.CharField(max_length=255)),
                ('online_order', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PREORDER', 'Preorder'), ('AWAITING', 'Awaiting Delivery'), ('RECEIVED', 'Received')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transactions.purchase')),
            ],
            options={
                'db_table': 'purchase_line_items',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('platform', models.CharField(max_length=255)),
                ('shipping_paid_by', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_url', models.URLField(blank=True, null=True)),
                ('buyer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transactions.sale')),
            ],
            options={
                'db_table': 'sale_line_items',
            },
        ),
        migrations.AddIndex(
            model_name='opening',
            index=models.Index(fields=['user'], name='openings_user_id_bf5576_idx'),
        ),
        migrations.AddIndex(
            model_name='opening',
            index=models.Index(fields=['opened_date'], name='openings_opened__b89645_idx'),
        ),
        migrations.AddIndex(
            model_name='openinglineitem',
            index=models.Index(fields=['opening'], name='opening_lin_opening_7275d4_idx'),
        ),
        migrations.AddIndex(
            model_name='openinglineitem',
            index=models.Index(fields=['product'], name='opening_lin_product_45c706_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='purchases_user_id_1d1d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='purchases_purchas_3b0bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='purchases_status_12ed65_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaselineitem',
            index=models.Index(fields=['purchase'], name='purchase_li_purchas_3eb263_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaselineitem',
            index=models.Index(fields=['product'], name='purchase_li_product_725ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user'], name='sales_user_id_ab37dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_da_0f99d4_idx'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['sale'], name='sale_line_i_sale_id_1fc706_idx'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['product'], name='sale_line_i_product_b0b002_idx'),
        ),
    ]
